AllCops:
  DisplayCopNames: true
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Exclude:
    - Brewfile
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'

Lint/RescueWithoutErrorClass:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Metrics/AbcSize:
  Max: 22.23

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/conversation.rb'
    - 'app/models/user.rb'

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false
