language: ruby

services:
  - mongodb
  - redis-server

rvm:
  - 2.7.0

addons:
  chrome: stable

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - nvm install 12
  - node -v
  - npm i -g yarn@^1.21.1
  - yarn
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_script:
  - bundle exec rake db:mongoid:create_indexes
