language: ruby

rvm:
  - 2.6.3

services:
  - mongodb
  - redis-server

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle exec rake db:mongoid:create_indexes
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
