language: ruby

services:
  - redis-server

rvm:
  - 2.7.1

addons:
  chrome: stable
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.4

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - nvm install 12
  - node -v
  - npm i -g yarn@^1.21.1
  - yarn
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_script:
  - psql -c 'create database "icare_test";' -U postgres
  - bundle exec rails g rgeo_supports_geos db:schema:load
