development:
  clients:
    default:
      database: icare_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: icare_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

staging:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
       connect_timeout: 15

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
       connect_timeout: 15
