development:
  clients:
    default:
      database: icare_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: icare_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

staging:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
       connect_timeout: 15
       retry_reads: <%= ENV['MONGODB_MODERN_RETRYABLE_READS'] || false %>
       retry_writes: <%= ENV['MONGODB_MODERN_RETRYABLE_WRITES'] || false %>

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
       connect_timeout: 15
       retry_reads: <%= ENV['MONGODB_MODERN_RETRYABLE_READS'] || false %>
       retry_writes: <%= ENV['MONGODB_MODERN_RETRYABLE_WRITES'] || false %>
